# Disallowed fns
[[disallowed-methods]]
path = "min_sqlite3_sys::operations::Operations::execute"
replacement = "min_sqlite3_sys::operations::Operations::execute_prepared"
reason = "prefer using `execute_prepared` to avoid SQL injection."

# Disallowed types
[[disallowed-types]]
path = "std::error::Error"
reason = "Please create & use an error specifically for lpm."
